### ISSUE TITLE
sporadic runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by tleyden** [couchbaselabs/cbfs#138]
I'm getting this error:

```
2014/12/13 01:24:57 http: panic serving 127.0.0.1:49634: runtime error: invalid memory address or nil pointer dereference
goroutine 955 [running]:
net/http.func·009()
    /usr/lib/go/src/pkg/net/http/server.go:1093 +0xae
runtime.panic(0x7b1100, 0xc9f2a8)
    /usr/lib/go/src/pkg/runtime/panic.c:248 +0x106
main.doGetUserDoc(0x7f3dec9c60d8, 0xc21013d3e0, 0xc21030a750)
    /opt/go/src/github.com/couchbaselabs/cbfs/http.go:521 +0xe94
main.doGet(0x7f3dec9bbfe0, 0xc21022da00, 0xc21030a750)
    /opt/go/src/github.com/couchbaselabs/cbfs/http.go:701 +0x1582
main.httpHandler(0x7f3dec9bbfe0, 0xc21022da00, 0xc21030a750)
    /opt/go/src/github.com/couchbaselabs/cbfs/http.go:849 +0x12c
net/http.HandlerFunc.ServeHTTP(0x8eb768, 0x7f3dec9bbfe0, 0xc21022da00, 0xc21030a750)
    /usr/lib/go/src/pkg/net/http/server.go:1220 +0x40
net/http.serverHandler.ServeHTTP(0xc21008d190, 0x7f3dec9bbfe0, 0xc21022da00, 0xc21030a750)
    /usr/lib/go/src/pkg/net/http/server.go:1597 +0x16e
net/http.(*conn).serve(0xc2102ee280)
    /usr/lib/go/src/pkg/net/http/server.go:1167 +0x7b7
created by net/http.(*Server).Serve
    /usr/lib/go/src/pkg/net/http/server.go:1644 +0x28b
2014/12/13 01:24:57 Recorded myself as an owner of f7ff9e8b7bb2e09b70935a5d785e0cc5d9d0abf0: result=success
```

Code that reproduces the (sporadic) error:

```

    // Create a cbfs client
    cbfs, err := cbfsclient.New(config.CbfsUrl)
    if err != nil {
        return err
    }

    // write to random cbfs file
    options := cbfsclient.PutOptions{
        ContentType: "text/plain",
    }

    content := "Hello"
    destPath := "env_check.txt"
    buffer := bytes.NewBuffer([]byte(content))

    if err := cbfs.Put("", destPath, buffer, options); err != nil {
        return fmt.Errorf("Error writing %v to cbfs: %v", destPath, err)
    }

    // read contents from cbfs file
    reader, err := cbfs.Get(destPath)
    if err != nil {
        return err
    }
    defer reader.Close()

    bytes, err := ioutil.ReadAll(reader)
    if err != nil {
        return err
    }

    if string(bytes) != content {
        return fmt.Errorf("Content did not match expected")
    }

    // delete contents on cbfs
    if err := cbfs.Rm(destPath); err != nil {
        return err
    }
    return nil
```

The `err` object returned from above code seems to be on the GET request:

```
Get http://localhost:8484/env_check.txt: EOF
```

**Comment by bchavez** [comment]
@tleyden , could you possibly push a new release on http://cbfs-ext.hq.couchbase.com/dist/ . The binaries seem to be out of date as I'm currently running into this nil pointer issue.

**Comment by tleyden** [comment]
@bchavez not sure I'll be able to get to it, but I'll walk you through building it yourself.  It's very easy to build!

Which OS are you on?

**Comment by bchavez** [comment]
@tleyden No problem, only a suggestion: maybe it's best to take the out-dated binaries offline if they can't be maintained. I'm slightly concerned hosting out-dated binaries put people at risk for 0-day security issues like #130 that I previously reported. Dustin mentioned there was a [`dist/update.sh`](https://github.com/couchbaselabs/cbfs/blob/master/dist/update.sh) script builds and publishes the binaries into your internal CBFS if no destination is specified. Otherwise, I'll just build from here.

**Comment by tleyden** [comment]
Great point.  OK I'll eventually get around to this, just can't make any promises on ETA.
